# https://tools.shajon.dev/curl-converter | By SHAJON-404

import requests
import json

url = 'https://b.i.instagram.com/api/v1/bloks/async_action/com.bloks.www.bloks.caa.login.async.send_login_request/'

headers = {
    "accept-language": "en-US",
    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
    "ig-intended-user-id": "0",
    "priority": "u=3",
    "x-bloks-is-layout-rtl": "false",
    "x-bloks-prism-button-version": "CONTROL",
    "x-bloks-prism-colors-enabled": "false",
    "x-bloks-prism-extended-palette-gray": "false",
    "x-bloks-prism-extended-palette-indigo": "true",
    "x-bloks-prism-extended-palette-polish-enabled": "false",
    "x-bloks-prism-extended-palette-red": "true",
    "x-bloks-prism-extended-palette-rest-of-colors": "true",
    "x-bloks-prism-font-enabled": "true",
    "x-bloks-prism-indigo-link-version": "1",
    "x-bloks-version-id": "3ae1e6445cdefeda05bde09f57499d84157ad74699044bf7fe9ca9183150f17a",
    "x-fb-client-ip": "True",
    "x-fb-connection-type": "WIFI",
    "x-fb-friendly-name": "IgApi: bloks/async_action/com.bloks.www.bloks.caa.login.async.send_login_request/",
    "x-fb-request-analytics-tags": json.dumps({
        "network_tags": {
            "product": "567067343352427",
            "surface": "undefined",
            "request_category": "api",
            "purpose": "fetch",
            "retry_attempt": "0",
        },
    }, separators=(',', ':')),
    "x-fb-server-cluster": "True",
    "x-ig-android-id": "android-f3cca9ec995dfdc3",
    "x-ig-app-id": "567067343352427",
    "x-ig-app-locale": "en_US",
    "x-ig-attest-params": json.dumps({
        "attestation": [
            {
                "version": 2,
                "type": "keystore",
                "errors": [
                    0,
                ],
                "challenge_nonce": "XEs1RGJYQZDt0xKU3m46fnOa2bAuMCBh",
                "signed_nonce": "MEQCIB6L1g6e2YqXAFKrraKq_RkqEL9ORf_R6B6mq5GkYVTRAiBHGP25iU_fAycKm-kK3jnkemY1DM-EKZcm2AwXieJ1SQ==",
                "key_hash": "8c5a91679fe92665a56f7f2d3a94c00258b60fbc8c4803ac2811b7ba3c634f28",
                "certificate_chain": "-----BEGIN CERTIFICATE-----\nMIICqTCCAk6gAwIBAgIBATAKBggqhkjOPQQDAjA5MQwwCgYDVQQMDANURUUxKTAnBgNVBAUTIDIx\nYjE0MjFiOGM0NWY5MDYzN2YxMzUxYjg1OWFkMWJhMB4XDTI2MDgwMjE0NDc0OFoXDTM2MDgwMjE0\nNDc0OFowHzEdMBsGA1UEAxMUQW5kcm9pZCBLZXlzdG9yZSBLZXkwWTATBgcqhkjOPQIBBggqhkjO\nPQMBBwNCAAQcDV+ZKBhcZKJdPgOAzUNoxCCV7EOkGDZ4PyDIC95GSNMflMwDcEU1j8Mz5lhriwqe\nas8lFAfsZ2923wGaI+FZo4IBXzCCAVswDwYDVR0PAQH/BAUDAweAADCCAUYGCisGAQQB1nkCAREE\nggE2MIIBMgIBZAoBAQIBZAoBAQQgQ3lRa2E1M3JLOGZlaTFWbUFncHRYd3ZCbnVVeGxqY0kEADBZ\nv4U9CAIGAZ/C8gvvv4VFSQRHMEUxHzAdBBVjb20uaW5zdGFncmFtLmFuZHJvaWQCBBbstIAxIgQg\nXz5Q9DVYPJrmJjAqcfc0AEQIen4sYK2s/CVCBamT4wUwgaShCDEGAgECAgEDogMCAQOjBAICAQCl\nBTEDAgEEqgMCAQG/g3cCBQC/hT4DAgEAv4VATDBKBCAi3jmUUyGW9hwDnpAmDXipOkxXNix+eJvp\nKANugLd8jAEB/woBAAQgd0vun7iO87aox6d9V70oJC0AsAIwTixM2jTeG4kNHuW/hUEFAgMCIuC/\nhUIFAgMDF2+/hU4GAgQBNSdhv4VPBgIEATUnYTAKBggqhkjOPQQDAgNJADBGAiEApoLAoeFgjtLA\n7ClLF4NmSQUjY6Lfa+WqdA89ZQVAXnsCIQCzSxcVFlvdU52/TU2a9PvnBP4ZvdjAG20/X77+wbCa\nFg==\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIB8jCCAXmgAwIBAgIQYlPVGNNL3e8p/E9N+V7Q3TAKBggqhkjOPQQDAjA5MQwwCgYDVQQMDANU\nRUUxKTAnBgNVBAUTIDhjMmI3NWE1ZWRmZDMwMmQ2ODY4NmE3OTlmNzVhMjZmMB4XDTIwMDEwNzIw\nNDQyOFoXDTMwMDEwNDIwNDQyOFowOTEMMAoGA1UEDAwDVEVFMSkwJwYDVQQFEyAyMWIxNDIxYjhj\nNDVmOTA2MzdmMTM1MWI4NTlhZDFiYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABBuSrZHvd0l9\n5BOYJScn1Wf+533457zvWuTBTs+E86Hq5VBg5y9EHoDqjX4OzLZls57IrVEfc/97ABZ9JyAP4XKj\nYzBhMB0GA1UdDgQWBBREJzaSycHkXVRIO+jeQ34WyIogDzAfBgNVHSMEGDAWgBQaaV4GJt0nU9ad\nJzsXVcokQPrb2zAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwICBDAKBggqhkjOPQQDAgNn\nADBkAjBSQeo3CsaANw4FE9FGQAuq2qgEaykd10TKTHGMDFk2V/CuKd2fVdnE5Q9/qQX+1ccCMBw1\n9d1XMQCvH3K3UkC7bPfCPtohev8wglCDXecvRZayQ7lsZVt7N8N+GH/8ry4kng==\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIDkzCCAXugAwIBAgIQR3MehuTP7Ng4yxyddZmaDzANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQF\nExBmOTIwMDllODUzYjZiMDQ1MB4XDTIwMDEwNzIwNDMyN1oXDTMwMDEwNDIwNDMyN1owOTEMMAoG\nA1UEDAwDVEVFMSkwJwYDVQQFEyA4YzJiNzVhNWVkZmQzMDJkNjg2ODZhNzk5Zjc1YTI2ZjB2MBAG\nByqGSM49AgEGBSuBBAAiA2IABNE/SEkiCznBEcuTYIxlBCy7f5sY81ZScvoOO7VfqmVraLP1KYkg\nQzxnSqfqp2JlKxcNQnHjKL756Y/gbmOp/S99uggOgKxC7Fo8R7VsNvr9sLELm3GcjXHbjU6YWSpX\n+KNjMGEwHQYDVR0OBBYEFBppXgYm3SdT1p0nOxdVyiRA+tvbMB8GA1UdIwQYMBaAFDZh4QB8iAUJ\nUYtEbEf/GkzJ6k8SMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgIEMA0GCSqGSIb3DQEB\nCwUAA4ICAQB7/bLXqh5H8sxNS5bHN8KC4ylHIKWRcX2qiNxGqPHEdjB4OLzampVerBrHaZto7tVe\nlF/Gny5piVgvCHlJKA0MQEJlCJXlKk6ZBPeY2o2+JVQUDtop84ShIvO/S+8UfcdYifYbuA+zd4k3\nJE1hjJTd3/O9Vi3NiorOUcmxZCGcFScEz0n0Tftq46WlzlvD4ew+Sh5cHSTYNxWgZVPka/GfzjHn\nmCCjAWXUgLmYJf3BHLp1P5wuph2bwXt+onrhXAaNrVmKz27XT52n44hUfeOOyJgsGNLct2NVmiHY\ncknWkcStPUzeJHJYz5IxxfGMxXjAeqi3ZojeWicLEPJ8Z0WyYR9KANBkTB00SnBfEqs2yliStdRv\nC1dxhOlXGL4EjGvZ61a065uVKCTT9iBxI6SeNvUnfDOZp2viaGhHKm6uC8hsr19Y9pDjK6MG36If\n1xUHjBSU6SQA2/462E4lo++TQOCIm7DaKwt/S6Ui9WICFrngDryvRvrMSpOd5K9vJEXPZMpyT6VD\nOY5ntbNQmHj01hpYBYZXbAbzl62SBY0w7NjUq3qE8hdm7SOas5Ph8Kk9SQGWmDdnZuppbiK7f7ab\nRRBmtNNN6z2gjDCQYhXQAQEBa27Tec3IGk+Vwzvp4CH42Yhpc1rpwl92AOQGX5S1446cYMkLZBda\n6O2b73AnZQ==\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIFHDCCAwSgAwIBAgIJAPHBcqaZ6vUdMA0GCSqGSIb3DQEBCwUAMBsxGTAXBgNVBAUTEGY5MjAw\nOWU4NTNiNmIwNDUwHhcNMjIwMzIwMTgwNzQ4WhcNNDIwMzE1MTgwNzQ4WjAbMRkwFwYDVQQFExBm\nOTIwMDllODUzYjZiMDQ1MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAr7bHgiuxpwHs\nK7Qui8xUFmOr75gvMsd/dTEDDJdSSxtf6An7xyqpRR90PL2abxM1dEqlXnf2tqw1Ne4Xwl5jlRfd\nnJLmN0pTy/4lj4/7tv0Sk3iiKkypnEUtR6WfMgH0QZfKHM1+di+y9TFRtv6y//0rb+T+W8a9nsNL\n/ggjnar86461qO0rOs2cXjp3kOG1FEJ5MVmFmBGtnrKpa73XpXyTqRxB/M0n1n/W9nGqC4FSYa04\nT6N5RIZGBN2z2MT5IKGbFlbC8UrW0DxW7AYImQQcHtGl/m00QLVWutHQoVJYnFPlXTcHYvASLu+R\nhhsbDmxMgJJ0mcDpvsC4PjvB+TxywElgS70vE0XmLD+OJtvsBslHZvPBKCOdT0MS+tgSOIfga+z1\nZ1g7+DVagf7quvmag8jfPioyKvxnK/EgsTUVi2ghzq8wm27ud/mIM7AY2qEORR8Go3TVB4HzWQgp\nZrt3i5MIlCaY504LzSRiigHCzAPlHws+W0rB5N+er5/2pJKnfBSDiCiFAVtCLOZ7gLiMm0jhO2B6\ntUXHI/+MRPjy02i59lINMRRev56GKtcd9qO/0kUJWdZTdA2XoS82ixPvZtXQpUpuL12ab+9EaDK8\nZ4RHJYYfCT3Q5vNAXaiWQ+8PTWm2QgBR/bkwSWc+NpUFgNPN9PvQi8WEg5UmAGMCAwEAAaNjMGEw\nHQYDVR0OBBYEFDZh4QB8iAUJUYtEbEf/GkzJ6k8SMB8GA1UdIwQYMBaAFDZh4QB8iAUJUYtEbEf/\nGkzJ6k8SMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgIEMA0GCSqGSIb3DQEBCwUAA4IC\nAQB8cMqTllHc8U+qCrOlg3H7174lmaCsbo/bJ0C17JEgMLb4kvrqsXZs01U3mB/qABg/1t5Pd5AO\nRHARs1hhqGICW/nKMav574f9rZN4PC2ZlufGXb7sIdJpGiO9ctRhiLuYuly10JccUZGEHpHSYM2G\ntkgYbZba6lsCPYAAP83cyDV+1aOkTf1RCp/lM0PKvmxYN10RYsK631jrleGdcdkxoSK//mSQbgcW\nnmAEZrzHoF1/0gso1HZgIn0YLzVhLSA/iXCX4QT2h3J5z3znluKG1nv8NQdxei2DIIhASWfu804C\nA96cQKTTlaae2fweqXjdN1/v2nqOhngNyz1361mFmr4XmaKH/ItTwOe72NI9ZcwS1lVaCvsIkTDC\nEXdm9rCNPAY10iTunIHFXRh+7KPzlHGewCq/8TOohBRn0/NNfh7uRslOSZ/xKbN9tMBtw37Z8d2v\nvnXq/YWdsm1+JLVwn6yYD/yacNJBlwpddla8eaVMjsF6nBnIgQOf9zKSe06nSTqvgwUHosgOECZJ\nZ1EuzbH4yswbt02tKtKEFhx+v+OTge/06V+jGsqTWLsfrOCNLuA8H++z+pUENmpqnnHovaI47gC+\nTNpkgYGkkBT6B/m/U01BuOBBTzhIlMEZq9qkDWuM2cA5kW5V3FJUcfHnw1IdYIg2Wxg7yHcQZemF\nQg==\n-----END CERTIFICATE-----",
            },
        ],
    }, separators=(',', ':')),
    "x-ig-bandwidth-speed-kbps": "-1.000",
    "x-ig-bandwidth-totalbytes-b": "0",
    "x-ig-bandwidth-totaltime-ms": "0",
    "x-ig-client-endpoint": "com.bloks.www.caa.login.login_homepage:com.bloks.www.caa.login.login_homepage",
    "x-ig-capabilities": "3brTv10=",
    "x-ig-connection-type": "WIFI",
    "x-ig-device-id": "5688f368-6663-4508-8e90-95f7c3575efe",
    "x-ig-device-locale": "en_US",
    "x-ig-family-device-id": "e8ea88fd-1ddc-4ea5-8e8b-e63b7e1c8018",
    "x-ig-is-foldable": "false",
    "x-ig-mapped-locale": "en_US",
    "x-ig-timezone-offset": "21600",
    "x-ig-www-claim": "0",
    "x-mid": "am9YlQABAAFrV5m8qqFy4ZBI-b6X",
    "x-meta-usdid": "1220b8cc-d389-4479-ac97-fd94c9344fc7.1785685673.MEUCIQDsbPXbXuxB5Ls8AkzNmWiO5qlbTGsG5L5zR5YMcldebwIgJaapho1ykdp5Akv9p1wm-z0SkE6diqWs8X2F9uHa7JA",
    "x-pigeon-rawclienttime": "1785682158.323",
    "x-pigeon-session-id": "UFS-3191c03a-639d-4468-a3da-9e349947dc52-2",
    "x-tigon-is-retry": "False",
    "x-zero-balance": "",
    "x-zero-eh": "IG0e09d776530888418ab70f3822fbb4e1",
    "user-agent": "Instagram 440.1.0.46.86 Android (34/14; 436dpi; 1080x2400; TECNO; TECNO CK7n; TECNO-CK7n; mt6789; en_US; 1028057441)",
    "x-fb-conn-uuid-client": "463370d19f0ec4e5317d49aeae149afa",
    "x-fb-http-engine": "Tigon/MNS/TCP",
}

data = {
    "params": json.dumps({
        "client_input_params": {
            "blocked_uids": [],
            "aac": json.dumps({
                "aac_init_timestamp": 1785682073,
                "aacjid": "6e697e01-0f96-48c6-864a-d06ac55de102",
                "aaccs": "tzu4rHYgX5gyB4K15awJcvvp0fs58xWQXL4aeZlN-bM",
            }, separators=(',', ':')),
            "sim_phones": [],
            "aymh_accounts": [],
            "network_bssid": None,
            "secure_family_device_id": "",
            "has_granted_read_contacts_permissions": 0,
            "auth_secure_device_id": "",
            "has_whatsapp_installed": 1,
            "password": "#PWD_INSTAGRAM:4:1785682158:AV4s7XhJgt9jsnG1WoAAARtui52haIlWTVG7O9CeqIdRKXEp4psFWueePJiQ/SPEHnbwFP10epv8R6kl8PoEaGMwUhJ+Rf8T1yZLyfIlTvawH6pcFjeRekQcjxKRVe96q/3uSDHW2lvBvhVYiYWsQbqL4wG7Qg7kvbh+nwG4iYyyxKE5lj3nSyD1/fifQTnnMOhZp+WnHa/MfBXbHt+A/KgLBC0FlxXgbBY0N2TcnkLeXm1X5cUxLOANDpRbn+gB7edlPWRIBXeCbsVP2IQUCvq2PSlbuHsZmBe90DTbsvVIiTc7/eaIbjySfnPqN5eSdYDYZtRC0dIXt0X7ZAQ34aAZvjS+mSu9ZvbtLY5KsULdZaZIY4DCJ/oxTtpPffUfduJ6Dm4S2LyWgQ==",
            "sso_token_map_json_string": "",
            "block_store_machine_id": "",
            "ig_vetted_device_nonces": None,
            "cloud_trust_token": None,
            "event_flow": "login_manual",
            "password_contains_non_ascii": "false",
            "client_known_key_hash": "",
            "sso_accounts_auth_data": [],
            "encrypted_msisdn": "",
            "has_granted_read_phone_permissions": 0,
            "app_manager_id": "",
            "should_show_nested_nta_from_aymh": 0,
            "device_id": "android-f3cca9ec995dfdc3",
            "zero_balance_state": "",
            "login_attempt_count": 1,
            "machine_id": "am9YlQABAAFrV5m8qqFy4ZBI-b6X",
            "flash_call_permission_status": {
                "READ_PHONE_STATE": "DENIED",
                "READ_CALL_LOG": "DENIED",
                "ANSWER_PHONE_CALLS": "DENIED",
            },
            "accounts_list": [
                {
                    "credential_type": "whatsapp_pre_linking_info_fetch",
                    "account_type": "Whatsapp",
                    "wa_data_bundle": "Q63UBTMeziFAPP6bGKAJKNBnvurZvEQ7IvCv4mJnArU7Uq13-N7b6suNx0gKQgrxSJS_cbtlcN1I-pSOwP6KYuGU6SXGaJ4Vs_ua-0psIEFhQvTUQjhQXFJu2xqL2lLEzdn6EVWZ2MB_jYAgWbQ7WWBUR6yF8wCgIlGOP7M3COlRwEqXhzgXpDf_FBvGpE9d-v1X1UPUneFl1fbIvc2FJUhln7iCYKn1YThdDXeRsx4J5ChIBxad9IovNVay-bUcwEcJSi0-w2W1V4M-Eal1asxVis8nP7StKZk-6pAKo3yFDLW4inaim7vk92a92juhbhr4W-H_KROw2mhwersuZ7ydpha83aB7ACDSaWeb7Y-TCsqFd7cLYt-CagUky9tsmJYqZ2HRnFEWvYr6oJZANJa8STZik4dn0reIn92rkn3tY9H_WhJvfc23mpnTRXhABngYKDbXA4qCawTrFlybIdKilc41l3JlNwSMuE3ZBCF_mw",
                    "wa_authproof": None,
                },
            ],
            "gms_incoming_call_retriever_eligibility": "eligible",
            "family_device_id": "e8ea88fd-1ddc-4ea5-8e8b-e63b7e1c8018",
            "fb_ig_device_id": [],
            "device_emails": [],
            "try_num": 1,
            "lois_settings": {
                "lois_token": "",
            },
            "event_step": "home_page",
            "headers_infra_flow_id": "",
            "openid_tokens": {},
            "contact_point": "z. zuck",
        },
        "server_params": {
            "should_trigger_override_login_2fa_action": 0,
            "is_from_logged_out": 0,
            "should_trigger_override_login_success_action": 0,
            "login_credential_type": "none",
            "server_login_source": "login",
            "waterfall_id": "44dadf4f-108e-46b0-8985-e65e733ab524",
            "two_step_login_type": "one_step_login",
            "login_source": "Login",
            "is_platform_login": 0,
            "login_entry_point": "logged_out",
            "INTERNAL__latency_qpl_marker_id": 36707139,
            "is_from_aymh": 0,
            "offline_experiment_group": "caa_iteration_v3_perf_ig_4",
            "is_from_landing_page": 0,
            "left_nav_button_action": "BACK",
            "password_text_input_id": "x0q9f0:107",
            "is_from_empty_password": 0,
            "is_from_msplit_fallback": 0,
            "ar_event_source": "login_home_page",
            "qe_device_id": "5688f368-6663-4508-8e90-95f7c3575efe",
            "username_text_input_id": "x0q9f0:106",
            "layered_homepage_experiment_group": "Deploy: Not in Experiment",
            "device_id": "android-f3cca9ec995dfdc3",
            "login_surface": "login_home",
            "INTERNAL__latency_qpl_instance_id": 199660906800244,
            "reg_flow_source": "nta_native_integration_point",
            "is_caa_perf_enabled": 1,
            "credential_type": "password",
            "is_from_password_entry_page": 0,
            "caller": "gslr",
            "family_device_id": "e8ea88fd-1ddc-4ea5-8e8b-e63b7e1c8018",
            "is_from_assistive_id": 0,
            "access_flow_version": "pre_mt_behavior",
            "is_from_logged_in_switcher": 0,
        },
    }),
    "bk_client_context": json.dumps({
        "bloks_version": "3ae1e6445cdefeda05bde09f57499d84157ad74699044bf7fe9ca9183150f17a",
        "styles_id": "instagram",
    }, separators=(',', ':')),
    "bloks_versioning_id": "3ae1e6445cdefeda05bde09f57499d84157ad74699044bf7fe9ca9183150f17a",
}

response = requests.post(url, headers=headers, data=data)
print(f"Response Status Code: {response.status_code}")
print(f"Response Body: {response.text}")